services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pedidos-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-orders:
    image: postgres:16-alpine
    container_name: pedidos-db-orders
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    volumes:
      - orders-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d orders']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-inventory:
    image: postgres:16-alpine
    container_name: pedidos-db-inventory
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - inventory-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d inventory']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-payments:
    image: postgres:16-alpine
    container_name: pedidos-db-payments
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    volumes:
      - payments-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d payments']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-notifications:
    image: postgres:16-alpine
    container_name: pedidos-db-notifications
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    volumes:
      - notifications-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d notifications']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq-data:
  orders-data:
  inventory-data:
  payments-data:
  notifications-data:
